### ISSUE TITLE
Create some constants out of variables based on the user

### ISSUE THREAD

**Issue by DicksHalfwayInn** [angelsix/blueberry#10]
We may be able to turn some variables into constants, with a notification message to acknowledge it was done.

I am basing this on the fact that people are creatures of habit, probably more-so for diabetics, as they know what works and doesn't work for themselves personally.

here is what I am talking about...

we have a variable for exercise input, but the person might already have a weekly pre-set routine for exercise... 

they may go to water polo twice a week, Mondays and Thursday, for one hour
they may walk with their partner 3 times a week for 1/2 an hour.
they may play floor hockey every Wednesday for 2 hours from sept 1- dec 15.
and then again from Jan 15- april 15.
they might be a skydiver twice a month during the summer.

a simple notification system that asks the user if they attended the session, might be able to automatically update the exercise variable.

The same thing can be used for food intake (carb intake):

If a person enters a baseline normal then a simple acknowledgement might be all that is necessary.  For example....

Luke said in his video that he normally drinks 15 cups of coffee a day... 
that could be a baseline input.... and at the end of the day, the program could ask... was this a normal day?   did you seriously drink 15 cups or was it something different?
The user can then during the end of day wrap up screen, before going to bed, update the information with actual information, as opposed to the norm.

So this brings me to another aspect that we should consider of the program....

should we insist that the program require users to complete a mid morning update and an update prior to going to bed.

**Comment by DicksHalfwayInn** [comment]
here is another example...

let's say that every time Stuart goes to work he usually stops and eats a McDonald's Breakfast wrap sandwich.  We can calculate the carbohydrate readings of this breakfast wrap sandwich and we, through history, know how it effects stuart normally.  We also know that stuart always has a chicken Caesar salad for lunch, bought at the local gas station on his way to work.  We, through history, know that this Caesar salad effects stuart's blood glucose readings x amount.  and stuart drinks coffee and beer, so we know that these will affect his readings based on input of beer and coffee.

based on the fact that people usually do the same things everyday, if that is in fact the case, we could set up notifications to ask the user to update information...

for example....

If we ask the user at 9:00 am... did you have your normal Mcdonald's breakfast this morning?
then we can update the carb intake based on their input.
at 2:00pm we could ask them... did you eat your normal chicken Caesar salad for lunch?
if not, then enter another...
we can ask the user... did you attend waterpolo today?
did you attend skydiving today?
did you walk with your partner today?
it is September 15, did you start floor hockey this week?

**Comment by angelsix** [comment]
I think we have various things here. 

Firstly, step back one step and before automated routines, we should add the ability to have normal manual input routines, and before that the ability to even log exercise, diet and other things.

So I think we need a few ideas making

1. Future plan for Exercise, Food, Insulin pages
2. Future plan for Routines page that can automate entries into each of the pages above
3. Future plan for Automated Routines as described briefly above

I will create those 3 ideas and we can continue each discussion there

**Comment by angelsix** [comment]
Closed now. Discussion continues in the linked issues above. For future ideas, please start the title of the issue with IDEA: so its easier to see, tag and move to the IDEA of the project https://github.com/angelsix/blueberry/projects/1
