### ISSUE TITLE
Constant engagement

### ISSUE THREAD

**Issue by DicksHalfwayInn** [angelsix/blueberry#11]
Although annoying to have constant pop-up windows asking for people to update their information, I think it is a really big part of the potential of this program.  The users have downloaded the app because they want to monitor their variables and input information. Reminders to do these things I think are really important.  In saying that, I think that it is really important to make updates of information as painless as possible.

The update to information might be as simple as weight recording or as complex as a carbohydrate calculation over time and insulin effectiveness based on current conditions.

but each can have a simple, or more difficult type of input.

I guess, what I am saying is that it is very easy for a user to add or edit a notification as opposed to taking the time to enter information.  If I have to remember to enter information onto my phone about every time I:
- take a current glucose reading, 
- do exercise, 
- quantify that exercise, 
- inject or take insulin, 
- estimate food carb intake, 
- take insulin based on what I know about predicting my insulin level in the future 

it gets old, really fast.  but if I get a pop-up notification saying "hi... I notice it is 9:00 am on Tuesday, and you have already told me that you normally get 7 hours sleep on Monday nights, prior to going to work.   Normally you eat porridge with a little bit of honey and go for a 1/2 hour walk with your girlfriends walking group on Tuesday mornings, prior to work .... I just want to confirm, for your diabetes app...
that, this  was this morning's routine!
 you can edit these things by checking or unchecking the box.
- Normal breakfast?
- Normal exercise?
- weight reading
- insulin intake reading?
- glucose reading?
- stress level?

**Comment by angelsix** [comment]
Referenced in new Idea issue. Closing, please continue discussions in new issue
